name: CI

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Type check
        run: npm run ts-check
      - name: Prettier
        run: npm run prettier:check:ci
      - name: ESLint
        run: npm run eslint
      - name: Test
        run: npm run test

  diff:
    runs-on: ubuntu-24.04
    environment: prod
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Assume role
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - name: Synth
        run: npm run cdk:synth
      - name: Diff
        uses: corymhall/cdk-diff-action@v2
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          failOnDestructiveChanges: false
